name = "show-do-miau"
compatibility_date = "2026-04-22"
workers_dev = true
main = "worker.js"

[observability]
enabled = false

[vars]
GENERATIVE_API_URL = "https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash-lite:generateContent"
GENERATIVE_SERVER_URL = "https://api-quizia.farigab.com/"
FRONTEND_ORIGIN = "https://quizia.farigab.com"
