#!/usr/bin/env node
const fs = require('node:fs');
const path = require('node:path');

const serverBase = process.env.SERVER_BASE || process.env.SHOWDO_SERVER_BASE || '';
const buildId = process.env.BUILD_ID || new Date().toISOString();
const outPath = path.join(process.cwd(), 'public', 'config.js');

const content = `// Auto-generated by scripts/generate-config.js\n` +
  `globalThis.SHOWDO_CONFIG = globalThis.SHOWDO_CONFIG || {};\n` +
  `globalThis.SHOWDO_CONFIG.serverBase = ${JSON.stringify(serverBase)};\n` +
  `globalThis.SHOWDO_CONFIG.buildId = ${JSON.stringify(buildId)};\n`;

try {
  fs.writeFileSync(outPath, content, 'utf8');
  console.log(`Wrote ${outPath} with serverBase=${serverBase || '<empty>'} buildId=${buildId}`);
} catch (err) {
  console.error('Failed to write config.js:', err);
  process.exit(1);
}
