#!/usr/bin/env node
const fs = require('node:fs');
const path = require('node:path');

const serverBase = process.env.SERVER_BASE || process.env.SHOWDO_SERVER_BASE || '';
const buildId = process.env.BUILD_ID || new Date().toISOString();
const outPath = path.join(process.cwd(), 'public', 'config.js');

const content = `// Auto-generated by scripts/generate-config.js\n` +
  `globalThis.SHOWDO_CONFIG = globalThis.SHOWDO_CONFIG || {};\n` +
  `globalThis.SHOWDO_CONFIG.serverBase = ${JSON.stringify(serverBase)};\n` +
  `globalThis.SHOWDO_CONFIG.buildId = ${JSON.stringify(buildId)};\n`;

try {
  fs.writeFileSync(outPath, content, 'utf8');
  console.log(`Wrote ${outPath} with serverBase=${serverBase || '<empty>'} buildId=${buildId}`);

  // Patch public/index.html to include buildId query strings for main assets
  try {
    const indexPath = path.join(process.cwd(), 'public', 'index.html');
    if (fs.existsSync(indexPath)) {
      let index = fs.readFileSync(indexPath, 'utf8');
      const safeBuildId = encodeURIComponent(buildId);
      index = index.replaceAll(/href="styles\.css(\?[^\"]*)?"/g, `href="styles.css?v=${safeBuildId}"`);
      index = index.replaceAll(/src="app\.js(\?[^\"]*)?"/g, `src="app.js?v=${safeBuildId}"`);
      fs.writeFileSync(indexPath, index, 'utf8');
      console.log(`Patched ${indexPath} with buildId=${buildId}`);
    }
  } catch (err) {
    console.warn('Failed to patch index.html with buildId:', err);
  }
} catch (err) {
  console.error('Failed to write config.js:', err);
  process.exit(1);
}
