#!/usr/bin/env node
const fs = require('node:fs');
const path = require('node:path');

const serverBase = process.env.SERVER_BASE || process.env.SHOWDO_SERVER_BASE || '';
// Use a filesystem-safe build id (timestamp) so we can include it in filenames.
const buildId = process.env.BUILD_ID || String(Date.now());
const serviceWorkerFile = `service-worker.${buildId}.js`;
const outPath = path.join(process.cwd(), 'public', 'config.js');

const content = `// Auto-generated by scripts/generate-config.js\n` +
  `globalThis.SHOWDO_CONFIG = globalThis.SHOWDO_CONFIG || {};\n` +
  `globalThis.SHOWDO_CONFIG.serverBase = ${JSON.stringify(serverBase)};\n` +
  `globalThis.SHOWDO_CONFIG.buildId = ${JSON.stringify(buildId)};\n` +
  `globalThis.SHOWDO_CONFIG.serviceWorkerFile = ${JSON.stringify(serviceWorkerFile)};\n`;

try {
  fs.writeFileSync(outPath, content, 'utf8');
  console.log(`Wrote ${outPath} with serverBase=${serverBase || '<empty>'} buildId=${buildId}`);
} catch (err) {
  console.error('Failed to write config.js:', err);
  process.exit(1);
}

// Also write a JSON version so clients can fetch the latest config without
// executing a script (avoids CSP/unsafe-eval and allows cache-busting fetches).
try {
  const outJson = path.join(process.cwd(), 'public', 'config.json');
  const enableSWenv = process.env.ENABLE_SW;
  const enableSW = enableSWenv === undefined ? undefined : (enableSWenv === 'false' ? false : (enableSWenv === 'true' ? true : undefined));
  const jsonObj = { serverBase, buildId, serviceWorkerFile };
  if (enableSW !== undefined) jsonObj.enableSW = enableSW;

  fs.writeFileSync(outJson, JSON.stringify(jsonObj), 'utf8');
  console.log(`Wrote ${outJson}`);
} catch (err) {
  console.error('Failed to write config.json:', err);
  process.exit(1);
}
